export default () => {
  return [
    {
      _id: '5b404ccec6ba2947a8e67df8',
      username: 'Winnifred.Torp',
      firstName: 'Thora',
      lastName: 'Vandervort',
      description: 'payment Computer',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/jitachi/128.jpg',
      location: 'Illinois',
      url: 'http://santina.info',
      email: 'Elise95@gmail.com',
      password: '$2a$10$dU4yajKHyEw72W9n0ciajuajvlQJrZF7iq5w2EwOin5qhapR0o7AW',
      created_at: '2018-03-10T09:35:20.592Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67df9',
      username: 'Aaliyah44',
      firstName: 'Andre',
      lastName: 'Halvorson',
      description: 'open-source Saudi Riyal Indiana',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/aio___/128.jpg',
      location: 'West Virginia',
      url: 'https://lavinia.info',
      email: 'Charlie73@hotmail.com',
      password: '$2a$10$DDQbWfE2ChVYjoCsjEQcJuVCueb.OgFcNgrveT44ubwZoXn4SyAEm',
      created_at: '2017-03-01T01:34:04.421Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dfa',
      username: 'Frida.Lemke42',
      firstName: 'Loren',
      lastName: 'Haley',
      description: 'efficient array Consultant',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/snowshade/128.jpg',
      location: 'New York',
      url: 'http://everardo.biz',
      email: 'Desmond.Crist99@gmail.com',
      password: '$2a$10$u.m7MR1gm8l2Awpnl4abJeVJ3YhJALC20Ztb6qcIQfi5e39tPuNqa',
      created_at: '2017-03-27T02:12:57.333Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dfb',
      username: 'Cheyenne_Kuphal14',
      firstName: 'Enos',
      lastName: 'Kutch',
      description: 'Dale deposit copying',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/gonzalorobaina/128.jpg',
      location: 'North Dakota',
      url: 'https://antonia.name',
      email: 'Tobin_Kihn@gmail.com',
      password: '$2a$10$IQZWmxPAd2WGUjisCk7ayOf6MXOAPfdZNca5vTAcy.AcmjOO6ENtK',
      created_at: '2018-02-11T20:22:29.316Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dfc',
      username: 'Dexter77',
      firstName: 'Felicity',
      lastName: 'Rath',
      description: 'Associate Designer SMS',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/joshhemsley/128.jpg',
      location: 'Kentucky',
      url: 'https://darryl.org',
      email: 'Daija4@yahoo.com',
      password: '$2a$10$krJGQV53ttG21ij2oLhYUO0gTjgb/P57jwvK1vIjrkt4Fj4vI4SJ6',
      created_at: '2017-03-05T16:30:43.360Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dfd',
      username: 'Tessie.Kris13',
      firstName: 'Esther',
      lastName: 'Kovacek',
      description: 'Mills Identity',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/andrewcohen/128.jpg',
      location: 'Utah',
      url: 'http://tremaine.biz',
      email: 'Leonor_OHara@hotmail.com',
      password: '$2a$10$UK46bQqSB3X75zUWp/eRMub0L9CbL19vt1Vjd3Xjs1X03M9TmYW/6',
      created_at: '2018-04-18T08:10:02.674Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dfe',
      username: 'Dayana14',
      firstName: 'Americo',
      lastName: 'Fisher',
      description: 'back up',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/nateschulte/128.jpg',
      location: 'Indiana',
      url: 'http://merle.com',
      email: 'Dolly1@yahoo.com',
      password: '$2a$10$TxbLWJQcXKr.In5K7SDlsu9dWLM/RrSs7ieduHDis.DTU82qQ472O',
      created_at: '2017-01-14T11:37:23.892Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67dff',
      username: 'Valentina_Hilll51',
      firstName: 'Pablo',
      lastName: 'Shields',
      description: 'Bahamian Dollar Liaison',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/davidmerrique/128.jpg',
      location: 'Oklahoma',
      url: 'http://rashad.biz',
      email: 'Kendrick2@hotmail.com',
      password: '$2a$10$Vuu0MQk.iAxbcJpAzojxhOWW/CfVxIFcPafHSiBplj9F6OgNoaV.2',
      created_at: '2018-03-17T04:40:58.563Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67e00',
      username: 'Akeem82',
      firstName: 'Alene',
      lastName: 'Mann',
      description: 'Falkland Islands Pound payment',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/kosmar/128.jpg',
      location: 'Delaware',
      url: 'http://rosalia.org',
      email: 'Makenna.Raynor62@yahoo.com',
      password: '$2a$10$M9MlbhUOWvKR03H/4Yn7IO5uOUCXL5UFJWHT6TkAgRhgVXX4olYpe',
      created_at: '2017-10-06T23:29:54.582Z',
    },
    {
      _id: '5b404ccec6ba2947a8e67e01',
      username: 'Rossie.Larson',
      firstName: 'Lillian',
      lastName: 'Gibson',
      description: 'protocol hub',
      profile_image_url:
        'https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg',
      location: 'Georgia',
      url: 'http://mavis.info',
      email: 'Abner.Ernser93@hotmail.com',
      password: '$2a$10$qdYqyimhafN7tGnNPNIXf.lwrH2ItlFQjbDmex2Md8XVvlKH.HRAm',
      created_at: '2018-04-18T18:04:36.869Z',
    },
  ];
};
